### PR TITLE
Use mgmcoPing.send

### PR DESCRIPTION
**Pull request by harianus**
In [this code](https://github.com/mgmco/tracking/blob/b5a65cf038e3e2df17e09e0168b74d73c759985f/scripts/build.js#L44) it looks like we can use `mgmcoPing.send(...)`, so I updated the docs.

Please read this carefully. 

cc @mgmco/developers

### CODE REVIEW

**Comment by mtimofiiv** [comment]
@chrissvo [`refresh()` is an alias for `send()` now](https://github.com/mgmco/tracking/blob/develop/test/test.js#L32).

However, @harianus, we do not return an `error` into the callback. We instead [catch and send the error to our heartbeat API](https://github.com/mgmco/tracking/blob/develop/src/ping.js#L134).

The callback will only get triggered in the case of success, so it's similar to the way `Promise`'s `resolve` works.

**Comment by harianus** [comment]
> The callback will only get triggered in the case of success, so it's similar to the way `Promise`'s `resolve` works.

Is this needed to be documented? I would say that in case of an error it is more useful, right?

**Comment by mtimofiiv** [comment]
> Is this needed to be documented? I would say that in case of an error it is more useful, right?

Now that you mention it, perhaps it would be good to document this.

I believe that if we do `send(data, (error, response) => {})` we are leaving it up to our clients to do an implementation for error handling, which I believe is wrong. In the current way we handle any errors that might arise ourselves.

I also don't know what a client would even do with one of our errors. From their perspective, the sale is made, and they are trying to send data to us.

One idea to resolve this is if they pass a second function, like an error handler, into it after the callback. But then once again, what would they do with this error?

**Comment by harianus** [comment]
Removed the callback for now.

**Comment by harianus** [comment]
Can you rereview @mtimofiiv

**Pull request merged**
